import io
import json
import tempfile
import unittest
from pathlib import Path

from modlab.cli import main
from modlab.workspace import initialize_workspace
from tests.support.mo2_bootstrap import make_primary_policy_fixture


CORE = (
    "Skyrim.esm",
    "Update.esm",
    "Dawnguard.esm",
    "HearthFires.esm",
    "Dragonborn.esm",
)


class Mo2CompareCliTests(unittest.TestCase):
    def make_instance(self, directory: str):
        layout = initialize_workspace(Path(directory, "ModLab", "workspace"))
        game_root = Path(
            directory,
            "Steam",
            "steamapps",
            "common",
            "Skyrim Special Edition",
        )
        make_primary_policy_fixture(game_root, ccc_plugins=())
        (layout.skyrim_mo2_app / "ModOrganizer.exe").write_bytes(b"fake mo2")
        primary = "\n".join(CORE) + "\n"
        for name in ("ModLab - Lab", "ModLab - Play"):
            profile = layout.skyrim_mo2_profiles / name
            profile.mkdir()
            (profile / "modlist.txt").write_text("+B\n+A\n", encoding="utf-8")
            (profile / "plugins.txt").write_text(
                "# This file was automatically generated by Mod Organizer.\n",
                encoding="utf-8",
            )
            (profile / "loadorder.txt").write_text(primary, encoding="utf-8")
            (profile / "settings.ini").write_text(
                "[General]\nLocalSaves=false\nLocalSettings=true\n",
                encoding="utf-8",
            )
        (layout.skyrim_mo2_app / "ModOrganizer.ini").write_text(
            (
                "[General]\n"
                f"gamePath={game_root.as_posix()}\n"
                "selected_profile=@ByteArray(ModLab - Lab)\n"
                "[Settings]\n"
                f"base_directory={layout.skyrim_mo2.as_posix()}\n"
                "download_directory=%BASE_DIR%/downloads\n"
                "mod_directory=%BASE_DIR%/mods\n"
                "profiles_directory=%BASE_DIR%/profiles\n"
                "overwrite_directory=%BASE_DIR%/overwrite\n"
            ),
            encoding="utf-8",
        )
        return layout, game_root

    @staticmethod
    def file_bytes(root: Path):
        return {
            path.relative_to(root).as_posix(): path.read_bytes()
            for path in root.rglob("*")
            if path.is_file()
        }

    @staticmethod
    def tree_entries(root: Path):
        return tuple(
            sorted(
                (
                    path.relative_to(root).as_posix(),
                    "directory" if path.is_dir() else "file",
                )
                for path in root.rglob("*")
            )
        )

    def run_compare(self, layout, game_root, *, output_format="json"):
        stdout, stderr = io.StringIO(), io.StringIO()
        code = main(
            [
                "manager",
                "compare",
                "mo2",
                "--root",
                str(layout.skyrim_mo2_app),
                "--game-root",
                str(game_root),
                "--workspace",
                str(layout.root),
                "--format",
                output_format,
            ],
            stdout,
            stderr,
        )
        return code, stdout.getvalue(), stderr.getvalue()

    def test_ready_json_is_complete_read_only_and_creates_no_workspace_output(self):
        with tempfile.TemporaryDirectory() as directory:
            layout, game_root = self.make_instance(directory)
            before_files = self.file_bytes(layout.root)
            before_tree = self.tree_entries(layout.root)

            code, stdout, stderr = self.run_compare(layout, game_root)

            result = json.loads(stdout)
            self.assertEqual(0, code)
            self.assertEqual("Ready", result["managerComparison"]["readiness"])
            self.assertEqual(
                "Play-to-Lab", result["managerComparison"]["direction"]
            )
            self.assertEqual(
                "complete",
                result["managerComparison"]["coverage"]["profileState"],
            )
            self.assertEqual([], result["actionsPerformed"])
            self.assertEqual(before_files, self.file_bytes(layout.root))
            self.assertEqual(before_tree, self.tree_entries(layout.root))
            self.assertEqual("", stderr)

    def test_lab_only_mod_reports_json_placement_between_shared_anchors(self):
        with tempfile.TemporaryDirectory() as directory:
            layout, game_root = self.make_instance(directory)
            lab = layout.skyrim_mo2_profiles / "ModLab - Lab" / "modlist.txt"
            lab.write_text("+B\n+X\n+A\n", encoding="utf-8")

            code, stdout, _ = self.run_compare(layout, game_root)

            change = json.loads(stdout)["managerComparison"]["differences"][
                "modChanges"
            ][0]
            self.assertEqual(0, code)
            self.assertEqual("X", change["name"])
            self.assertEqual("added-in-lab", change["change"])
            self.assertEqual(1, change["labPosition"]["sequenceIndex"])
            self.assertEqual("A", change["labPosition"]["previousSharedAnchor"])
            self.assertEqual("B", change["labPosition"]["nextSharedAnchor"])

    def test_plugin_mismatch_and_missing_settings_return_blocked_null_state(self):
        cases = ("plugin", "settings")
        for case in cases:
            with self.subTest(case=case), tempfile.TemporaryDirectory() as directory:
                layout, game_root = self.make_instance(directory)
                lab = layout.skyrim_mo2_profiles / "ModLab - Lab"
                if case == "plugin":
                    (lab / "loadorder.txt").write_text(
                        "\n".join(CORE + ("Unknown.esp",)) + "\n",
                        encoding="utf-8",
                    )
                else:
                    (lab / "settings.ini").unlink()

                code, stdout, stderr = self.run_compare(layout, game_root)
                manager = json.loads(stdout)["managerComparison"]

                self.assertEqual(3, code)
                self.assertEqual("Blocked", manager["readiness"])
                self.assertIsNone(manager["adapterState"])
                self.assertIsNone(manager["adapterStateSha256"])
                self.assertIsNone(manager["differences"])
                self.assertEqual("", stderr)

    def test_unknown_executable_version_is_contextual_and_ready(self):
        with tempfile.TemporaryDirectory() as directory:
            layout, game_root = self.make_instance(directory)

            code, stdout, _ = self.run_compare(layout, game_root)
            manager = json.loads(stdout)["managerComparison"]

            self.assertEqual(0, code)
            self.assertEqual("Ready", manager["readiness"])
            self.assertIsNone(
                manager["observationContext"]["executable"]["fileVersion"]
            )

    def test_text_explains_placement_coverage_and_no_side_effects(self):
        with tempfile.TemporaryDirectory() as directory:
            layout, game_root = self.make_instance(directory)
            lab = layout.skyrim_mo2_profiles / "ModLab - Lab" / "modlist.txt"
            lab.write_text("+B\n+X\n+A\n", encoding="utf-8")

            code, text, stderr = self.run_compare(
                layout, game_root, output_format="text"
            )

            self.assertEqual(0, code)
            self.assertTrue(
                text.startswith(
                    "Ready: all required MO2 profile-state evidence was compared."
                )
            )
            self.assertIn("Lab placement: index 1; previous A; next B", text)
            self.assertIn("Coverage limit:", text)
            self.assertTrue(
                text.rstrip().endswith(
                    "Nothing was launched, changed, installed, repaired, promoted, or downloaded."
                )
            )
            self.assertEqual("", stderr)

    def test_thirty_entry_reorder_text_window_is_bounded(self):
        with tempfile.TemporaryDirectory() as directory:
            layout, game_root = self.make_instance(directory)
            play = tuple(f"Entry-{index:02d}" for index in range(30))
            lab = list(play)
            lab[12], lab[13] = lab[13], lab[12]
            for profile_name, sequence in (
                ("ModLab - Play", play),
                ("ModLab - Lab", tuple(lab)),
            ):
                path = layout.skyrim_mo2_profiles / profile_name / "modlist.txt"
                path.write_text(
                    "".join(f"+{name}\n" for name in reversed(sequence)),
                    encoding="utf-8",
                )

            code, text, _ = self.run_compare(
                layout, game_root, output_format="text"
            )

            self.assertEqual(0, code)
            self.assertIn("First divergence: 12", text)
            self.assertLessEqual(text.count("Play["), 7)
            self.assertLessEqual(text.count("Lab["), 7)

    def test_discover_json_retains_its_original_exact_field_set(self):
        with tempfile.TemporaryDirectory() as directory:
            layout, game_root = self.make_instance(directory)
            stdout, stderr = io.StringIO(), io.StringIO()

            code = main(
                [
                    "manager",
                    "discover",
                    "mo2",
                    "--root",
                    str(layout.skyrim_mo2_app),
                    "--game-root",
                    str(game_root),
                    "--workspace",
                    str(layout.root),
                    "--format",
                    "json",
                ],
                stdout,
                stderr,
            )

            evidence = json.loads(stdout.getvalue())["managerEvidence"]
            self.assertEqual(0, code)
            self.assertEqual(
                {
                    "schemaVersion",
                    "adapterId",
                    "requestedRoot",
                    "resolvedRoot",
                    "gameRoot",
                    "executable",
                    "portableConfigPresent",
                    "configuredGamePath",
                    "paths",
                    "activeProfile",
                    "profiles",
                    "topLevelMods",
                    "modMetadataFiles",
                    "overwriteEntries",
                    "findings",
                    "actions",
                    "downloads",
                    "installations",
                    "programLaunches",
                },
                set(evidence),
            )
            self.assertEqual("", stderr.getvalue())


if __name__ == "__main__":
    unittest.main()
