"""Deterministic target classification and contained MO2 seed rendering."""

from __future__ import annotations

import hashlib
import json
import os
from collections.abc import Mapping
from pathlib import Path, PurePosixPath, PureWindowsPath
import stat

from modlab.adapters.skyrim.primary_plugins import (
    CORE_PRIMARY_PLUGINS,
    SkyrimPrimaryPluginError,
    observe_skyrim_primary_plugins,
)
from modlab.workspace import WorkspaceLayout

from .archive import PackageFile, PackageInventory
from .bootstrap_model import OptionalFileIdentity, ProfileSeedEvidence, TargetSnapshot
from .readset import Mo2ReadSet
from .release import Mo2ReleaseDescriptor


class Mo2BootstrapConfigError(RuntimeError):
    """Raised when a target or deterministic seed cannot be trusted."""


INI_NAMES = ("Skyrim.ini", "SkyrimPrefs.ini", "SkyrimCustom.ini")
PROFILE_NAMES = ("ModLab - Lab", "ModLab - Play")
PROFILE_SETTINGS = (
    b"[General]\n"
    b"LocalSaves=false\n"
    b"LocalSettings=true\n"
    b"AutomaticArchiveInvalidation=true\n"
)
LIST_HEADER = b"# This file was automatically generated by Mod Organizer.\n"

_SKELETON_NAMES = ("app", "downloads", "mods", "profiles", "overwrite")
_LIST_FILES = ("modlist.txt", "plugins.txt", "lockedorder.txt")
_PLUGIN_EXTENSIONS = {".esm", ".esl", ".esp"}


def classify_mo2_target(layout: WorkspaceLayout) -> TargetSnapshot:
    root = Path(layout.skyrim_mo2)
    try:
        root_metadata = root.lstat()
    except FileNotFoundError:
        return _target_snapshot("Empty", root, ())
    except OSError as error:
        return _target_snapshot(
            "Blocked",
            root,
            (
                {
                    "path": ".",
                    "kind": "unreadable",
                    "error": type(error).__name__,
                },
            ),
        )

    root_row = _metadata_row(".", root, root_metadata)
    if _redirected(root, root_metadata) or not stat.S_ISDIR(root_metadata.st_mode):
        return _target_snapshot("Blocked", root, (root_row,))

    try:
        entries = _direct_entry_rows(root)
    except OSError as error:
        return _target_snapshot(
            "Blocked",
            root,
            (
                root_row,
                {
                    "path": ".",
                    "kind": "unreadable",
                    "error": type(error).__name__,
                },
            ),
        )

    rows: list[dict[str, object]] = list(entries)
    names = tuple(str(item["path"]) for item in entries)
    folded = tuple(item.casefold() for item in names)
    unique = len(folded) == len(set(folded))
    exact_names = set(folded) == set(_SKELETON_NAMES) and len(entries) == len(
        _SKELETON_NAMES
    )
    if unique and exact_names:
        try:
            empty = all(
                _is_direct_empty_directory(root / name)
                for name in _SKELETON_NAMES
            )
        except OSError:
            empty = False
        if empty:
            return _target_snapshot("Empty", root, tuple(rows))

    app = root / "app"
    try:
        app_metadata = app.lstat()
    except OSError:
        return _target_snapshot("Blocked", root, tuple(rows))
    if _redirected(app, app_metadata) or not stat.S_ISDIR(app_metadata.st_mode):
        return _target_snapshot("Blocked", root, tuple(rows))
    executable = app / "ModOrganizer.exe"
    try:
        executable_metadata = executable.lstat()
    except OSError:
        return _target_snapshot("Blocked", root, tuple(rows))
    if _redirected(executable, executable_metadata) or not stat.S_ISREG(
        executable_metadata.st_mode
    ):
        rows.append(
            _metadata_row("app/ModOrganizer.exe", executable, executable_metadata)
        )
        return _target_snapshot("Blocked", root, tuple(rows))
    try:
        executable_data = _stable_bytes(executable)
    except OSError:
        return _target_snapshot("Blocked", root, tuple(rows))
    rows.append(
        {
            "path": "app/ModOrganizer.exe",
            "kind": "file",
            "redirected": False,
            "sha256": hashlib.sha256(executable_data).hexdigest(),
            "size": len(executable_data),
        }
    )
    return _target_snapshot("Existing", root, tuple(rows))


def observe_profile_seed(
    game_root: Path,
    documents_root: Path,
    *,
    read_set: Mo2ReadSet | None = None,
) -> ProfileSeedEvidence:
    observer = read_set or Mo2ReadSet()
    documents = Path(documents_root).expanduser().absolute()
    _require_direct_directory(documents, "Documents root")
    game_ini_root = documents / "My Games" / "Skyrim Special Edition"
    _require_optional_direct_directory(documents / "My Games", "My Games directory")
    _require_optional_direct_directory(game_ini_root, "Skyrim INI directory")
    try:
        primary = observe_skyrim_primary_plugins(game_root, read_set=observer)
    except SkyrimPrimaryPluginError as error:
        raise Mo2BootstrapConfigError(str(error)) from error

    sources = tuple(
        _observe_optional_regular_file(game_ini_root / name, observer)
        for name in INI_NAMES
    )
    verification = observer.verify()
    if not verification.stable:
        raise Mo2BootstrapConfigError(
            "profile seed sources changed during observation: "
            + ", ".join(verification.changed_paths)
        )
    return ProfileSeedEvidence(
        documents_root=str(documents),
        primary_plugins=primary.plugins,
        skyrim_ccc=OptionalFileIdentity(
            path=primary.ccc_path,
            present=primary.ccc_present,
            sha256=primary.ccc_sha256,
            size=primary.ccc_size,
        ),
        ini_sources=sources,
    )


def render_modorganizer_ini(
    layout: WorkspaceLayout,
    game_root: Path,
    release: Mo2ReleaseDescriptor,
) -> bytes:
    game = str(Path(game_root).expanduser().absolute())
    base = str(Path(layout.skyrim_mo2).expanduser().absolute())
    game_value = _qsettings_byte_array(game)
    base_value = _qsettings_escaped_string(base)
    return (
        "[General]\n"
        "gameName=Skyrim Special Edition\n"
        "selected_profile=@ByteArray(ModLab - Lab)\n"
        f"gamePath={game_value}\n"
        "game_edition=Steam\n"
        f"version={release.product_version}\n"
        "first_start=false\n"
        "[Settings]\n"
        f"base_directory={base_value}\n"
        "profile_local_inis=true\n"
        "profile_local_saves=false\n"
        "profile_archive_invalidation=true\n"
    ).encode("utf-8")


def render_profile_files(
    seed: ProfileSeedEvidence,
    *,
    read_set: Mo2ReadSet | None = None,
) -> dict[PurePosixPath, bytes]:
    observer = read_set or Mo2ReadSet()
    _validate_primary_plugins(seed.primary_plugins)
    ccc_path = Path(seed.skyrim_ccc.path)
    if ccc_path.name != "Skyrim.ccc":
        raise Mo2BootstrapConfigError("profile seed has an unexpected Skyrim.ccc path")
    _require_direct_directory(ccc_path.parent, "Skyrim game root")
    _require_identity_unchanged(seed.skyrim_ccc, observer)
    ini_bytes = _reobserve_ini_sources(seed, observer)
    verification = observer.verify()
    if not verification.stable:
        raise Mo2BootstrapConfigError(
            "seed source changed during profile rendering: "
            + ", ".join(verification.changed_paths)
        )
    load_order = LIST_HEADER + "".join(
        f"{name}\n" for name in seed.primary_plugins
    ).encode("utf-8")
    files: dict[PurePosixPath, bytes] = {}
    for profile_name in PROFILE_NAMES:
        root = PurePosixPath("profiles", profile_name)
        files[root / "settings.ini"] = PROFILE_SETTINGS
        for name in _LIST_FILES:
            files[root / name] = LIST_HEADER
        files[root / "archives.txt"] = b""
        files[root / "loadorder.txt"] = load_order
        for name in INI_NAMES:
            files[root / name] = ini_bytes[name]
    return files


def write_staged_configuration(
    staging_root: Path,
    manager_ini: bytes,
    profile_files: Mapping[PurePosixPath, bytes],
) -> PackageInventory:
    if type(manager_ini) is not bytes:
        raise Mo2BootstrapConfigError("ModOrganizer.ini content must be bytes")
    stage = Path(staging_root).expanduser().absolute()
    _require_direct_directory(stage, "staging root")
    try:
        resolved_stage = stage.resolve(strict=True)
    except OSError as error:
        raise Mo2BootstrapConfigError("staging root cannot be resolved") from error
    if os.path.normcase(str(resolved_stage)) != os.path.normcase(str(stage)):
        raise Mo2BootstrapConfigError("staging root must not use redirected ancestors")
    app = stage / "app"
    _require_direct_directory(app, "staged app directory")

    expected_paths = _expected_profile_paths()
    actual_paths = set(profile_files)
    if actual_paths != expected_paths:
        raise Mo2BootstrapConfigError("profile file set is not the exact ModLab seed")
    if any(type(data) is not bytes for data in profile_files.values()):
        raise Mo2BootstrapConfigError("profile file content must be bytes")

    manager_path = app / "ModOrganizer.ini"
    profiles_root = stage / "profiles"
    if manager_path.exists() or profiles_root.exists():
        raise Mo2BootstrapConfigError("staged configuration already exists")

    written: list[PackageFile] = []
    try:
        profiles_root.mkdir()
        for profile_name in PROFILE_NAMES:
            (profiles_root / profile_name).mkdir()
        _write_exclusive(manager_path, manager_ini)
        written.append(_package_file("app/ModOrganizer.ini", manager_ini))
        for relative, data in sorted(
            profile_files.items(),
            key=lambda item: (
                item[0].as_posix().casefold(),
                item[0].as_posix(),
            ),
        ):
            target = stage.joinpath(*relative.parts)
            _write_exclusive(target, data)
            written.append(_package_file(relative.as_posix(), data))
    except OSError as error:
        raise Mo2BootstrapConfigError(
            f"staged configuration could not be written exclusively: {error}"
        ) from error

    files = tuple(
        sorted(
            written,
            key=lambda item: (item.relative_path.casefold(), item.relative_path),
        )
    )
    canonical = json.dumps(
        [[item.relative_path, item.sha256, item.size] for item in files],
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    return PackageInventory(
        files=files,
        total_size=sum(item.size for item in files),
        sha256=hashlib.sha256(canonical).hexdigest(),
    )


def _observe_optional_regular_file(
    path: Path, observer: Mo2ReadSet
) -> OptionalFileIdentity:
    try:
        data = observer.optional_bytes(path)
    except OSError as error:
        raise Mo2BootstrapConfigError(
            f"{path.name} is not a direct regular INI source"
        ) from error
    return OptionalFileIdentity(
        path=str(path),
        present=data is not None,
        sha256=None if data is None else hashlib.sha256(data).hexdigest(),
        size=None if data is None else len(data),
    )


def _reobserve_ini_sources(
    seed: ProfileSeedEvidence, observer: Mo2ReadSet
) -> dict[str, bytes]:
    if len(seed.ini_sources) != len(INI_NAMES):
        raise Mo2BootstrapConfigError("profile seed does not contain the exact INI sources")
    documents = Path(seed.documents_root)
    _require_direct_directory(documents, "Documents root")
    _require_optional_direct_directory(documents / "My Games", "My Games directory")
    root = documents / "My Games" / "Skyrim Special Edition"
    _require_optional_direct_directory(root, "Skyrim INI directory")
    result: dict[str, bytes] = {}
    for name, identity in zip(INI_NAMES, seed.ini_sources, strict=True):
        expected = root / name
        if os.path.normcase(identity.path) != os.path.normcase(str(expected)):
            raise Mo2BootstrapConfigError(f"profile seed has an unexpected {name} path")
        data = _require_identity_unchanged(identity, observer)
        result[name] = b"" if data is None else data
    return result


def _require_identity_unchanged(
    identity: OptionalFileIdentity, observer: Mo2ReadSet
) -> bytes | None:
    path = Path(identity.path)
    try:
        data = observer.optional_bytes(path)
    except OSError as error:
        raise Mo2BootstrapConfigError(
            f"seed source changed or became unsafe: {path.name}"
        ) from error
    present = data is not None
    sha256 = None if data is None else hashlib.sha256(data).hexdigest()
    size = None if data is None else len(data)
    if (present, sha256, size) != (identity.present, identity.sha256, identity.size):
        raise Mo2BootstrapConfigError(
            f"seed source changed after observation: {path.name}"
        )
    return data


def _validate_primary_plugins(plugins: tuple[str, ...]) -> None:
    if plugins[: len(CORE_PRIMARY_PLUGINS)] != CORE_PRIMARY_PLUGINS:
        raise Mo2BootstrapConfigError("profile seed is missing the fixed Skyrim masters")
    normalized = tuple(item.casefold() for item in plugins)
    if len(normalized) != len(set(normalized)):
        raise Mo2BootstrapConfigError("profile seed contains a duplicate primary plug-in")
    for name in plugins:
        if (
            not name
            or name != name.strip()
            or name in {".", ".."}
            or any(character in name for character in "/\\")
            or any(ord(character) < 32 for character in name)
            or name.casefold() == "saves"
            or PureWindowsPath(name).suffix.casefold() not in _PLUGIN_EXTENSIONS
        ):
            raise Mo2BootstrapConfigError("profile seed contains an unsafe primary plug-in")


def _qsettings_byte_array(value: str) -> str:
    if not value or any(ord(character) < 32 for character in value):
        raise Mo2BootstrapConfigError("QSettings path contains unsafe text")
    return "@ByteArray(" + value.replace("\\", "\\\\") + ")"


def _qsettings_escaped_string(value: str) -> str:
    if not value or any(ord(character) < 32 for character in value):
        raise Mo2BootstrapConfigError("QSettings path contains unsafe text")
    return value.replace("\\", "\\\\")


def _expected_profile_paths() -> set[PurePosixPath]:
    names = (
        "settings.ini",
        *_LIST_FILES,
        "archives.txt",
        "loadorder.txt",
        *INI_NAMES,
    )
    return {
        PurePosixPath("profiles", profile_name, name)
        for profile_name in PROFILE_NAMES
        for name in names
    }


def _write_exclusive(path: Path, data: bytes) -> None:
    with path.open("xb") as output:
        output.write(data)
        output.flush()
        os.fsync(output.fileno())


def _package_file(relative_path: str, data: bytes) -> PackageFile:
    return PackageFile(
        relative_path=relative_path,
        sha256=hashlib.sha256(data).hexdigest(),
        size=len(data),
    )


def _target_snapshot(
    kind: str, root: Path, rows: tuple[dict[str, object], ...]
) -> TargetSnapshot:
    ordered = tuple(
        sorted(
            rows,
            key=lambda item: (
                str(item.get("path", "")).casefold(),
                str(item.get("path", "")),
            ),
        )
    )
    canonical = json.dumps(
        ordered, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return TargetSnapshot(
        kind=kind,
        root=str(root),
        inventory_sha256=hashlib.sha256(canonical).hexdigest(),
        entry_count=len(ordered),
    )


def _direct_entry_rows(root: Path) -> tuple[dict[str, object], ...]:
    rows: list[dict[str, object]] = []
    with os.scandir(root) as entries:
        for entry in entries:
            path = Path(entry.path)
            metadata = entry.stat(follow_symlinks=False)
            rows.append(_metadata_row(entry.name, path, metadata))
    return tuple(rows)


def _metadata_row(path_text: str, path: Path, metadata) -> dict[str, object]:
    kind = "other"
    if stat.S_ISDIR(metadata.st_mode):
        kind = "directory"
    elif stat.S_ISREG(metadata.st_mode):
        kind = "file"
    row: dict[str, object] = {
        "path": path_text,
        "kind": kind,
        "redirected": _redirected(path, metadata),
    }
    if kind == "file":
        row["size"] = metadata.st_size
    return row


def _is_direct_empty_directory(path: Path) -> bool:
    metadata = path.lstat()
    if _redirected(path, metadata) or not stat.S_ISDIR(metadata.st_mode):
        return False
    with os.scandir(path) as entries:
        return next(entries, None) is None


def _require_direct_directory(path: Path, label: str) -> None:
    try:
        metadata = path.lstat()
    except OSError as error:
        raise Mo2BootstrapConfigError(f"{label} is missing or unreadable") from error
    if _redirected(path, metadata) or not stat.S_ISDIR(metadata.st_mode):
        raise Mo2BootstrapConfigError(f"{label} must be one direct directory")


def _require_optional_direct_directory(path: Path, label: str) -> None:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return
    except OSError as error:
        raise Mo2BootstrapConfigError(f"{label} cannot be inspected") from error
    if _redirected(path, metadata) or not stat.S_ISDIR(metadata.st_mode):
        raise Mo2BootstrapConfigError(f"{label} must be one direct directory")


def _redirected(path: Path, metadata) -> bool:
    attributes = getattr(metadata, "st_file_attributes", 0)
    return path.is_symlink() or bool(
        attributes & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    )


def _stable_bytes(path: Path) -> bytes:
    first = path.read_bytes()
    second = path.read_bytes()
    if first != second:
        raise OSError(f"file changed while reading: {path}")
    return first
